DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS` (
    EMAIL varchar(255) NOT NULL,
    PASSWORD varchar(255) NOT NULL
);

DROP TABLE IF EXISTS `TEXTURES`;
CREATE TABLE `TEXTURES` (
    EMAIL varchar(255) NOT NULL,
    TEXTURE varchar(1024) NOT NULL
)